KanjiOriginScreen:
	name: 'Credits'
	fullscreen: True
	#on_parent: if not args[1]: textinput.focus = False

    RstDocument:
	    text:
	        ('.. _top:\n'
			'\n'
			'Credits\n'
			'=======\n'
			'\n'
			'Thanks to the following people/organizations:\n\n'
			'**Software:** Python & Kivy\n\n'
			'**Kivy team on IRC in #kivy**\n\n'
			'**stackoverflow:**\n'
			'Totem\n\n'
			'**App testers:**\n\n'
			'* Need testers\n\n'
			'**Kanji Mnemonics:** http://kanji.koohii.com/ and it\'s users')
