#:kivy 1.9.1
#:import join os.path.join

KanjiOriginScreen:
    name: 'Credits'
    fullscreen: True
    #on_parent: if not args[1]: textinput.focus = False

    RstDocument:
        #base_font_size: 28 + self.height*.005  # default 31
        # - to make it even for computer screens (base_font_size is already in sp)
        base_font_size: 28 + self.height*.015 - sp(self.height*.005)
        text: open(join('data', 'screens', 'txt', 'credits.txt')).read()
