#:kivy 1.9.1
#:import dbmanager data.screens.dbmanager

#<DBScreen>:
##    AnchorLayout:
##        size_hint_y: None
##        height: max(root.height, content.height)
#    BoxLayout:
#        id: content
#        orientation: 'vertical'
#        spacing: '16dp'
#        padding: ['8dp', '24dp']

KanjiOriginScreen:
    name: 'DBmanager'
    fullscreen: True

    DatabaseManager:
        id: dbm
        on_current_screen:
            idx = self.screen_names.index(args[1].name)