KanjiOriginScreen:
	name: 'MainMenu'
	#fullscreen: True

	Button:
		size_hint_y: None
		height: '48dp'
		text: 'Learn Kanji'
		on_release: app.go_screen(1)

	Button:
		size_hint_y: None
		height: '48dp'
		text: 'Learning method info'
		on_release: app.go_screen(2)

	Button:
		size_hint_y: None
		height: '48dp'
		text: 'Donation :D'
		on_release: app.go_screen(3)

    Button:
		size_hint_y: None
		height: '48dp'
		text: 'Credits'
		on_release: app.go_screen(4)