<MainButton@Button>:
    size_hint_y: None
	height: '60dp'

KanjiOriginScreen:
	name: 'MainMenu'
	#fullscreen: True

	MainButton:
		text: 'Learn Kanji'
		on_release: app.go_screen(1)

	MainButton:
		text: 'Learning method info'
		on_release: app.go_screen(2)

	MainButton:
	    text: 'Backup & Restore'
	    on_release: app.go_screen(3)

	MainButton:
		text: 'Donation :D'
		on_release: app.go_screen(4)

    MainButton:
		text: 'Credits'
		on_release: app.go_screen(5)
