#:kivy 1.9.1
#:import koohiicsv data.screens.db_kv.koohiicsv


KoohiiCSV:
    name: 'KoohiiCSV'
    on_pre_enter: app.root.ids.actp.ac_prev = self.parent
    #on_pre_leave: app.root.ids.actp.ac_prev = app

    BoxLayoutS:
        orientation: 'vertical'

        DBinfo:
            text: root.lbtext

        ScaleButton:
            text: root.bttext
            on_release: root.callback()
            size_hint_y: .3
            disabled: True  # delete when function does something